# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-tick-tack-toe:
    hostname: localhost
    build: .
    image: gateway-tick-tack-toe
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8000:8000"
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
secrets:
  license:
    file: ./docker/license.xml
